# -*- coding: utf-8 -*-
"""
翻译工作线程 - Translation Worker Thread
"""

import time
import random
from typing import List, Dict, Any, Optional
from PyQt6.QtCore import QThread, pyqtSignal

from utils.logger import get_logger

# 尝试导入googletrans，如果失败则使用模拟翻译
try:
    from googletrans import Translator, LANGUAGES
    GOOGLETRANS_AVAILABLE = True
except ImportError:
    GOOGLETRANS_AVAILABLE = False
    from utils.mock_translator import MockTranslator


class TranslateWorker(QThread):
    """翻译工作线程"""
    
    translation_progress = pyqtSignal(int, int)
    translation_finished = pyqtSignal(list)
    translation_error = pyqtSignal(str)
    
    def __init__(self, texts: List[Dict[str, Any]], target_lang: str = "en → zh-cn"):
        super().__init__()
        self.texts = texts
        self.target_lang = target_lang
        self.logger = get_logger()
        self.stop_flag = False
        
        # 初始化翻译器
        if GOOGLETRANS_AVAILABLE:
            self.translator = Translator()
            self.logger.info("使用Google翻译API")
        else:
            self.translator = MockTranslator()
            self.logger.warning("Google翻译不可用，使用模拟翻译器")
    
    def run(self):
        """运行翻译"""
        try:
            translated_results = []
            total = len(self.texts)
            
            self.logger.info(f"开始翻译 {total} 条文本")
            
            for i, item in enumerate(self.texts):
                if self.stop_flag:
                    break
                
                original_text = item.get('original', '')
                if not original_text:
                    continue
                
                try:
                    # 执行翻译
                    translated_text = self.translate_text(original_text)
                    
                    # 更新结果
                    result = item.copy()
                    result['translation'] = translated_text
                    translated_results.append(result)
                    
                    # 发送进度信号
                    self.translation_progress.emit(i + 1, total)
                    
                    # 添加延迟避免API限制
                    time.sleep(random.uniform(0.5, 1.5))
                    
                except Exception as e:
                    self.logger.warning(f"翻译文本失败 '{original_text[:50]}...': {e}")
                    # 失败的文本保持原文
                    result = item.copy()
                    result['translation'] = original_text
                    translated_results.append(result)
            
            # 发送完成信号
            self.translation_finished.emit(translated_results)
            self.logger.info(f"翻译完成，成功翻译 {len(translated_results)} 条文本")
            
        except Exception as e:
            error_msg = f"翻译过程中发生错误: {str(e)}"
            self.logger.error(error_msg)
            self.translation_error.emit(error_msg)
    
    def translate_text(self, text: str) -> str:
        """翻译单个文本"""
        if not text.strip():
            return text
        
        # 解析目标语言
        if self.target_lang == "en → zh-cn":
            src_lang = 'en'
            dest_lang = 'zh-cn'
        elif self.target_lang == "zh-cn → en":
            src_lang = 'zh-cn'
            dest_lang = 'en'
        else:
            src_lang = 'auto'
            dest_lang = 'zh-cn'
        
        # 使用翻译器
        if GOOGLETRANS_AVAILABLE:
            try:
                result = self.translator.translate(text, src=src_lang, dest=dest_lang)
                return result.text
            except Exception as e:
                self.logger.warning(f"Google翻译失败，使用备用方法: {e}")
                return self.fallback_translate(text, dest_lang)
        else:
            return self.translator.translate(text, dest_lang)
    
    def fallback_translate(self, text: str, dest_lang: str) -> str:
        """备用翻译方法"""
        # 简单的翻译映射表（实际项目中可以扩展）
        translation_map = {
            'Hello': '你好',
            'World': '世界',
            'Welcome': '欢迎',
            'Game': '游戏',
            'Player': '玩家',
            'Server': '服务器',
            'Chat': '聊天',
            'Message': '消息',
            'Command': '命令',
            'Block': '方块',
            'Item': '物品',
            'Entity': '实体',
            'Boss': 'Boss',
            'Bar': '栏',
            'Name': '名称',
            'Title': '标题',
            'Text': '文本',
            'Click': '点击',
            'Open': '打开',
            'Close': '关闭',
            'Start': '开始',
            'Stop': '停止',
            'Yes': '是',
            'No': '否',
            'OK': '确定',
            'Cancel': '取消',
            'Save': '保存',
            'Load': '加载',
            'Delete': '删除',
            'Create': '创建',
            'Edit': '编辑',
            'View': '查看',
            'Settings': '设置',
            'Options': '选项',
            'Help': '帮助',
            'About': '关于',
            'Exit': '退出',
            'Quit': '退出',
            'Back': '返回',
            'Next': '下一步',
            'Previous': '上一步',
            'Finish': '完成',
            'Complete': '完成',
            'Success': '成功',
            'Failed': '失败',
            'Error': '错误',
            'Warning': '警告',
            'Info': '信息',
            'Debug': '调试',
            'Trace': '跟踪',
            'Log': '日志',
            'File': '文件',
            'Folder': '文件夹',
            'Directory': '目录',
            'Path': '路径',
            'Size': '大小',
            'Date': '日期',
            'Time': '时间',
            'Type': '类型',
            'Format': '格式',
            'Version': '版本',
            'Author': '作者',
            'Copyright': '版权',
            'License': '许可证',
            'Description': '描述',
            'Comment': '评论',
            'Note': '备注',
            'Tag': '标签',
            'Category': '分类',
            'Group': '组',
            'Class': '类',
            'Method': '方法',
            'Function': '函数',
            'Variable': '变量',
            'Constant': '常量',
            'Parameter': '参数',
            'Argument': '参数',
            'Return': '返回',
            'Result': '结果',
            'Output': '输出',
            'Input': '输入',
            'Data': '数据',
            'Database': '数据库',
            'Table': '表',
            'Record': '记录',
            'Field': '字段',
            'Column': '列',
            'Row': '行',
            'Index': '索引',
            'Key': '键',
            'Value': '值',
            'Object': '对象',
            'Array': '数组',
            'List': '列表',
            'Map': '映射',
            'Set': '集合',
            'String': '字符串',
            'Number': '数字',
            'Integer': '整数',
            'Float': '浮点数',
            'Boolean': '布尔值',
            'True': '真',
            'False': '假',
            'Null': '空',
            'None': '无',
            'Empty': '空',
            'Full': '满',
            'Half': '半',
            'Quarter': '四分之一',
            'Third': '三分之一',
            'Percent': '百分比',
            'Percentage': '百分比',
            'Ratio': '比例',
            'Rate': '比率',
            'Speed': '速度',
            'Velocity': '速度',
            'Acceleration': '加速度',
            'Force': '力',
            'Energy': '能量',
            'Power': '功率',
            'Pressure': '压力',
            'Temperature': '温度',
            'Heat': '热量',
            'Cold': '冷',
            'Warm': '温暖',
            'Hot': '热',
            'Light': '光',
            'Dark': '暗',
            'Bright': '明亮',
            'Dim': '暗淡',
            'Color': '颜色',
            'Red': '红色',
            'Green': '绿色',
            'Blue': '蓝色',
            'Yellow': '黄色',
            'Orange': '橙色',
            'Purple': '紫色',
            'Pink': '粉色',
            'Black': '黑色',
            'White': '白色',
            'Gray': '灰色',
            'Brown': '棕色',
            'Gold': '金色',
            'Silver': '银色',
            'Bronze': '青铜色',
            'Metal': '金属',
            'Wood': '木头',
            'Stone': '石头',
            'Dirt': '泥土',
            'Grass': '草',
            'Water': '水',
            'Fire': '火',
            'Air': '空气',
            'Earth': '土',
            'Sky': '天空',
            'Ground': '地面',
            'Floor': '地板',
            'Wall': '墙壁',
            'Roof': '屋顶',
            'Door': '门',
            'Window': '窗户',
            'Stairs': '楼梯',
            'Ladder': '梯子',
            'Bridge': '桥',
            'Road': '道路',
            'Path': '路径',
            'Track': '轨道',
            'Rail': '铁轨',
            'Train': '火车',
            'Car': '汽车',
            'Bus': '公交车',
            'Truck': '卡车',
            'Bike': '自行车',
            'Boat': '船',
            'Ship': '船',
            'Plane': '飞机',
            'Helicopter': '直升机',
            'Rocket': '火箭',
            'Satellite': '卫星',
            'Space': '太空',
            'Universe': '宇宙',
            'Galaxy': '星系',
            'Star': '星星',
            'Planet': '行星',
            'Moon': '月亮',
            'Sun': '太阳',
            'Earth': '地球',
            'Mars': '火星',
            'Venus': '金星',
            'Jupiter': '木星',
            'Saturn': '土星',
            'Mercury': '水星',
            'Uranus': '天王星',
            'Neptune': '海王星',
            'Pluto': '冥王星',
            'Comet': '彗星',
            'Asteroid': '小行星',
            'Meteor': '流星',
            'Nebula': '星云',
            'Black Hole': '黑洞',
            'Time': '时间',
            'Space': '空间',
            'Dimension': '维度',
            'Portal': '传送门',
            'Gateway': '网关',
            'Teleporter': '传送器',
            'Warp': '扭曲',
            'Jump': '跳跃',
            'Fly': '飞行',
            'Walk': '行走',
            'Run': '奔跑',
            'Swim': '游泳',
            'Climb': '攀爬',
            'Dig': '挖掘',
            'Mine': '开采',
            'Build': '建造',
            'Craft': '制作',
            'Smelt': '熔炼',
            'Cook': '烹饪',
            'Brew': '酿造',
            'Enchant': '附魔',
            'Repair': '修复',
            'Upgrade': '升级',
            'Level': '等级',
            'Experience': '经验',
            'Skill': '技能',
            'Ability': '能力',
            'Power': '力量',
            'Strength': '强度',
            'Defense': '防御',
            'Attack': '攻击',
            'Damage': '伤害',
            'Health': '生命值',
            'Life': '生命',
            'Mana': '魔法值',
            'Energy': '能量',
            'Stamina': '耐力',
            'Magic': '魔法',
            'Spell': '法术',
            'Curse': '诅咒',
            'Blessing': '祝福',
            'Potion': '药水',
            'Elixir': '灵药',
            'Food': '食物',
            'Drink': '饮料',
            'Bread': '面包',
            'Meat': '肉',
            'Fish': '鱼',
            'Fruit': '水果',
            'Vegetable': '蔬菜',
            'Apple': '苹果',
            'Orange': '橙子',
            'Banana': '香蕉',
            'Grape': '葡萄',
            'Cherry': '樱桃',
            'Strawberry': '草莓',
            'Watermelon': '西瓜',
            'Pineapple': '菠萝',
            'Mango': '芒果',
            'Peach': '桃子',
            'Pear': '梨',
            'Lemon': '柠檬',
            'Lime': '酸橙',
            'Coconut': '椰子',
            'Nut': '坚果',
            'Seed': '种子',
            'Grain': '谷物',
            'Wheat': '小麦',
            'Rice': '大米',
            'Corn': '玉米',
            'Potato': '土豆',
            'Carrot': '胡萝卜',
            'Tomato': '番茄',
            'Onion': '洋葱',
            'Garlic': '大蒜',
            'Pepper': '胡椒',
            'Salt': '盐',
            'Sugar': '糖',
            'Honey': '蜂蜜',
            'Milk': '牛奶',
            'Cheese': '奶酪',
            'Butter': '黄油',
            'Egg': '鸡蛋',
            'Chicken': '鸡肉',
            'Beef': '牛肉',
            'Pork': '猪肉',
            'Lamb': '羊肉',
            'Fish': '鱼肉',
            'Seafood': '海鲜',
            'Shrimp': '虾',
            'Crab': '螃蟹',
            'Lobster': '龙虾',
            'Oyster': '牡蛎',
            'Clam': '蛤蜊',
            'Mussel': '贻贝',
            'Squid': '鱿鱼',
            'Octopus': '章鱼',
            'Shark': '鲨鱼',
            'Whale': '鲸鱼',
            'Dolphin': '海豚',
            'Seal': '海豹',
            'Walrus': '海象',
            'Penguin': '企鹅',
            'Bear': '熊',
            'Wolf': '狼',
            'Fox': '狐狸',
            'Rabbit': '兔子',
            'Deer': '鹿',
            'Moose': '驼鹿',
            'Elk': '麋鹿',
            'Reindeer': '驯鹿',
            'Horse': '马',
            'Cow': '牛',
            'Pig': '猪',
            'Sheep': '羊',
            'Goat': '山羊',
            'Dog': '狗',
            'Cat': '猫',
            'Mouse': '老鼠',
            'Rat': '大鼠',
            'Hamster': '仓鼠',
            'Guinea Pig': '豚鼠',
            'Squirrel': '松鼠',
            'Chipmunk': '花栗鼠',
            'Beaver': '海狸',
            'Raccoon': '浣熊',
            'Skunk': '臭鼬',
            'Badger': '獾',
            'Otter': '水獭',
            'Weasel': '鼬',
            'Ferret': '雪貂',
            'Mink': '水貂',
            'Bat': '蝙蝠',
            'Bird': '鸟',
            'Eagle': '鹰',
            'Hawk': '隼',
            'Falcon': '猎鹰',
            'Owl': '猫头鹰',
            'Crow': '乌鸦',
            'Raven': '渡鸦',
            'Sparrow': '麻雀',
            'Robin': '知更鸟',
            'Cardinal': '红衣主教鸟',
            'Blue Jay': '蓝松鸦',
            'Woodpecker': '啄木鸟',
            'Parrot': '鹦鹉',
            'Canary': '金丝雀',
            'Finch': '雀',
            'Wren': '鹪鹩',
            'Thrush': '画眉',
            'Blackbird': '黑鸟',
            'Starling': '八哥',
            'Swallow': '燕子',
            'Swift': '雨燕',
            'Hummingbird': '蜂鸟',
            'Toucan': '巨嘴鸟',
            'Flamingo': '火烈鸟',
            'Stork': '鹳',
            'Heron': '苍鹭',
            'Crane': '鹤',
            'Pelican': '鹈鹕',
            'Albatross': '信天翁',
            'Seagull': '海鸥',
            'Duck': '鸭子',
            'Goose': '鹅',
            'Swan': '天鹅',
            'Peacock': '孔雀',
            'Turkey': '火鸡',
            'Chicken': '鸡',
            'Rooster': '公鸡',
            'Hen': '母鸡',
            'Chick': '小鸡',
            'Ostrich': '鸵鸟',
            'Emu': '鸸鹋',
            'Kiwi': '几维鸟',
            'Panda': '熊猫',
            'Koala': '考拉',
            'Kangaroo': '袋鼠',
            'Wallaby': '小袋鼠',
            'Wombat': '袋熊',
            'Platypus': '鸭嘴兽',
            'Echidna': '针鼹',
            'Tasmanian Devil': '袋獾',
            'Quokka': '短尾矮袋鼠',
            'Capybara': '水豚',
            'Sloth': '树懒',
            'Armadillo': '犰狳',
            'Anteater': '食蚁兽',
            'Tapir': '貘',
            'Peccary': '西猯',
            'Llama': '羊驼',
            'Alpaca': '羊驼',
            'Camel': '骆驼',
            'Giraffe': '长颈鹿',
            'Elephant': '大象',
            'Hippopotamus': '河马',
            'Rhinoceros': '犀牛',
            'Tiger': '老虎',
            'Lion': '狮子',
            'Leopard': '豹',
            'Jaguar': '美洲豹',
            'Cheetah': '猎豹',
            'Panther': '黑豹',
            'Cougar': '美洲狮',
            'Lynx': '猞猁',
            'Bobcat': '短尾猫',
            'Hyena': '鬣狗',
            'Jackal': '豺',
            'Wild Dog': '野狗',
            'Coyote': '郊狼',
            'Dingo': '澳洲野狗',
            'Reptile': '爬行动物',
            'Snake': '蛇',
            'Python': '蟒蛇',
            'Boa': '蟒蛇',
            'Cobra': '眼镜蛇',
            'Viper': '蝰蛇',
            'Rattlesnake': '响尾蛇',
            'Lizard': '蜥蜴',
            'Iguana': '鬣蜥',
            'Chameleon': '变色龙',
            'Gecko': '壁虎',
            'Turtle': '乌龟',
            'Tortoise': '陆龟',
            'Crocodile': '鳄鱼',
            'Alligator': '短吻鳄',
            'Dinosaur': '恐龙',
            'Dragon': '龙',
            'Phoenix': '凤凰',
            'Griffin': '狮鹫',
            'Unicorn': '独角兽',
            'Pegasus': '飞马',
            'Centaur': '半人马',
            'Minotaur': '弥诺陶洛斯',
            'Sphinx': '斯芬克斯',
            'Kraken': '北海巨妖',
            'Leviathan': '利维坦',
            'Behemoth': '贝希摩斯',
            'Golem': '魔像',
            'Zombie': '僵尸',
            'Skeleton': '骷髅',
            'Ghost': '幽灵',
            'Spirit': '灵魂',
            'Demon': '恶魔',
            'Angel': '天使',
            'Vampire': '吸血鬼',
            'Werewolf': '狼人',
            'Witch': '女巫',
            'Wizard': '巫师',
            'Mage': '法师',
            'Sorcerer': '术士',
            'Warlock': '术士',
            'Necromancer': '死灵法师',
            'Alchemist': '炼金术士',
            'Knight': '骑士',
            'Warrior': '战士',
            'Fighter': '斗士',
            'Paladin': '圣骑士',
            'Ranger': '游侠',
            'Rogue': '盗贼',
            'Thief': '小偷',
            'Assassin': '刺客',
            'Ninja': '忍者',
            'Samurai': '武士',
            'Viking': '维京人',
            'Pirate': '海盗',
            'Sailor': '水手',
            'Captain': '船长',
            'Admiral': '海军上将',
            'General': '将军',
            'Soldier': '士兵',
            'Warrior': '勇士',
            'Hero': '英雄',
            'Champion': '冠军',
            'Legend': '传奇',
            'Myth': '神话',
            'Fairy Tale': '童话',
            'Story': '故事',
            'Book': '书',
            'Page': '页',
            'Chapter': '章节',
            'Volume': '卷',
            'Series': '系列',
            'Collection': '集合',
            'Library': '图书馆',
            'Museum': '博物馆',
            'Gallery': '画廊',
            'Theater': '剧院',
            'Cinema': '电影院',
            'Concert': '音乐会',
            'Festival': '节日',
            'Celebration': '庆典',
            'Party': '派对',
            'Wedding': '婚礼',
            'Birthday': '生日',
            'Anniversary': '周年纪念',
            'Holiday': '假日',
            'Vacation': '假期',
            'Journey': '旅程',
            'Adventure': '冒险',
            'Expedition': '探险',
            'Quest': '任务',
            'Mission': '使命',
            'Challenge': '挑战',
            'Trial': '试炼',
            'Test': '测试',
            'Exam': '考试',
            'Competition': '比赛',
            'Tournament': '锦标赛',
            'Match': '比赛',
            'Game': '游戏',
            'Sport': '运动',
            'Exercise': '锻炼',
            'Training': '训练',
            'Practice': '练习',
            'Lesson': '课程',
            'Class': '班级',
            'School': '学校',
            'University': '大学',
            'College': '学院',
            'Academy': '学院',
            'Institute': '研究所',
            'Laboratory': '实验室',
            'Research': '研究',
            'Study': '学习',
            'Learn': '学习',
            'Teach': '教学',
            'Educate': '教育',
            'Knowledge': '知识',
            'Wisdom': '智慧',
            'Intelligence': '智力',
            'Understanding': '理解',
            'Comprehension': '理解',
            'Memory': '记忆',
            'Remember': '记住',
            'Forget': '忘记',
            'Recall': '回忆',
            'Recognize': '认出',
            'Identify': '识别',
            'Discover': '发现',
            'Find': '找到',
            'Search': '搜索',
            'Seek': '寻找',
            'Look': '看',
            'See': '看见',
            'Watch': '观看',
            'Observe': '观察',
            'Notice': '注意到',
            'Detect': '检测',
            'Sense': '感觉',
            'Feel': '感觉',
            'Touch': '触摸',
            'Hear': '听见',
            'Listen': '听',
            'Smell': '闻',
            'Taste': '尝',
            'Speak': '说话',
            'Talk': '谈话',
            'Say': '说',
            'Tell': '告诉',
            'Ask': '问',
            'Answer': '回答',
            'Reply': '回复',
            'Respond': '回应',
            'Shout': '喊叫',
            'Scream': '尖叫',
            'Whisper': '低语',
            'Murmur': '低语',
            'Sing': '唱歌',
            'Dance': '跳舞',
            'Play': '玩',
            'Perform': '表演',
            'Act': '表演',
            'Show': '展示',
            'Display': '显示',
            'Present': '呈现',
            'Demonstrate': '演示',
            'Explain': '解释',
            'Describe': '描述',
            'Define': '定义',
            'Clarify': '澄清',
            'Illustrate': '说明',
            'Exemplify': '举例',
            'Compare': '比较',
            'Contrast': '对比',
            'Differentiate': '区分',
            'Distinguish': '区别',
            'Identify': '识别',
            'Classify': '分类',
            'Categorize': '分类',
            'Organize': '组织',
            'Arrange': '安排',
            'Order': '命令',
            'Sort': '排序',
            'Group': '分组',
            'Separate': '分离',
            'Divide': '分割',
            'Combine': '结合',
            'Join': '加入',
            'Connect': '连接',
            'Link': '链接',
            'Attach': '附加',
            'Detach': '分离',
            'Remove': '移除',
            'Delete': '删除',
            'Erase': '擦除',
            'Clear': '清除',
            'Clean': '清洁',
            'Wash': '洗',
            'Wipe': '擦拭',
            'Brush': '刷',
            'Polish': '抛光',
            'Shine': '发光',
            'Glow': '发光',
            'Sparkle': '闪烁',
            'Glitter': '闪光',
            'Twinkle': '闪烁',
            'Flash': '闪光',
            'Blink': '眨眼',
            'Flicker': '闪烁',
            'Shimmer': '闪烁',
            'Glimmer': '微光',
            'Gleam': '闪烁',
            'Beam': '光束',
            'Ray': '光线',
            'Light': '光',
            'Lamp': '灯',
            'Lantern': '灯笼',
            'Torch': '火把',
            'Candle': '蜡烛',
            'Fire': '火',
            'Flame': '火焰',
            'Burn': '燃烧',
            'Heat': '加热',
            'Warm': '温暖',
            'Melt': '融化',
            'Freeze': '冻结',
            'Cool': '冷却',
            'Chill': '寒冷',
            'Ice': '冰',
            'Snow': '雪',
            'Frost': '霜',
            'Hail': '冰雹',
            'Rain': '雨',
            'Storm': '风暴',
            'Thunder': '雷',
            'Lightning': '闪电',
            'Wind': '风',
            'Breeze': '微风',
            'Gale': '大风',
            'Hurricane': '飓风',
            'Tornado': '龙卷风',
            'Typhoon': '台风',
            'Cloud': '云',
            'Fog': '雾',
            'Mist': '薄雾',
            'Steam': '蒸汽',
            'Smoke': '烟',
            'Dust': '灰尘',
            'Sand': '沙子',
            'Mud': '泥',
            'Clay': '粘土',
            'Brick': '砖',
            'Stone': '石头',
            'Rock': '岩石',
            'Boulder': '巨石',
            'Pebble': '卵石',
            'Gem': '宝石',
            'Crystal': '水晶',
            'Diamond': '钻石',
            'Emerald': '绿宝石',
            'Ruby': '红宝石',
            'Sapphire': '蓝宝石',
            'Opal': '蛋白石',
            'Jade': '玉',
            'Pearl': '珍珠',
            'Gold': '金',
            'Silver': '银',
            'Copper': '铜',
            'Iron': '铁',
            'Steel': '钢',
            'Bronze': '青铜',
            'Tin': '锡',
            'Lead': '铅',
            'Zinc': '锌',
            'Nickel': '镍',
            'Aluminum': '铝',
            'Titanium': '钛',
            'Platinum': '铂',
            'Uranium': '铀',
            'Obsidian': '黑曜石',
            'Quartz': '石英',
            'Granite': '花岗岩',
            'Marble': '大理石',
            'Limestone': '石灰石',
            'Sandstone': '砂岩',
            'Slate': '板岩',
            'Coal': '煤',
            'Charcoal': '木炭',
            'Oil': '油',
            'Gas': '气体',
            'Air': '空气',
            'Oxygen': '氧气',
            'Hydrogen': '氢气',
            'Nitrogen': '氮气',
            'Carbon': '碳',
            'Water': '水',
            'Steam': '蒸汽',
            'Ice': '冰',
            'Lava': '熔岩',
            'Magma': '岩浆',
            'Obsidian': '黑曜石',
            'Glass': '玻璃',
            'Crystal': '水晶',
            'Mirror': '镜子',
            'Lens': '透镜',
            'Prism': '棱镜',
            'Rainbow': '彩虹',
            'Spectrum': '光谱',
            'Color': '颜色',
            'Hue': '色调',
            'Shade': '阴影',
            'Tint': '色调',
            'Tone': '音调',
            'Pitch': '音高',
            'Volume': '音量',
            'Sound': '声音',
            'Noise': '噪音',
            'Music': '音乐',
            'Song': '歌曲',
            'Melody': '旋律',
            'Harmony': '和声',
            'Rhythm': '节奏',
            'Beat': '节拍',
            'Tempo': '速度',
            'Note': '音符',
            'Chord': '和弦',
            'Scale': '音阶',
            'Instrument': '乐器',
            'Piano': '钢琴',
            'Guitar': '吉他',
            'Violin': '小提琴',
            'Cello': '大提琴',
            'Flute': '长笛',
            'Trumpet': '小号',
            'Drum': '鼓',
            'Bell': '铃铛',
            'Chime': '钟声',
            'Organ': '风琴',
            'Harp': '竖琴',
            'Saxophone': '萨克斯',
            'Clarinet': '单簧管',
            'Oboe': '双簧管',
            'Bassoon': '巴松',
            'Trombone': '长号',
            'Tuba': '大号',
            'French Horn': '圆号',
            'Bugle': '军号',
            'Harmonica': '口琴',
            'Accordion': '手风琴',
            'Bagpipe': '风笛',
            'Banjo': '班卓琴',
            'Mandolin': '曼陀林',
            'Ukulele': '尤克里里',
            'Xylophone': '木琴',
            'Marimba': '马林巴琴',
            'Vibraphone': '颤音琴',
            'Glockenspiel': '钟琴',
            'Tambourine': '手鼓',
            'Cymbal': '钹',
            'Triangle': '三角铁',
            'Castanet': '响板',
            'Maraca': '沙锤',
            'Conga': '康加鼓',
            'Bongo': '邦戈鼓',
            'Tabla': '塔布拉鼓',
            'Djembe': '非洲鼓',
            'Didgeridoo': '迪吉里杜管',
            'Sitar': '西塔琴',
            'Tabla': '塔布拉鼓',
            'Sarangi': '萨朗吉琴',
            'Santoor': '桑图尔琴',
            'Bansuri': '班苏里笛',
            'Shehnai': '沙奈管',
            'Harmonium': ' harmonium风琴',
            'Tanpura': '坦普拉琴',
            'Ghatam': '陶罐鼓',
            'Mridangam': '姆里丹甘鼓',
            'Kanjeera': '坎吉拉鼓',
            'Morsing': '莫辛琴',
            'Jews Harp': '口簧琴',
            'Kazoo': '卡祖笛',
            'Whistle': '口哨',
            'Recorder': '竖笛',
            'Ocarina': '陶笛',
            'Pan Flute': '排箫',
            'Kalimba': '卡林巴琴',
            'Thumb Piano': '拇指琴',
            'Mbira': '姆比拉琴',
            'Lyre': '里拉琴',
            'Zither': '齐特琴',
            'Dulcimer': '扬琴',
            'Psaltery': '索尔特里琴',
            'Autoharp': '自动竖琴',
            'Hammered Dulcimer': '击弦扬琴',
            'Mountain Dulcimer': '山地扬琴',
            'Appalachian Dulcimer': '阿巴拉契亚扬琴',
            'Cimbalom': '钦巴龙',
            'Santur': '桑图尔琴',
            'Yangqin': '扬琴',
            'Guzheng': '古筝',
            'Koto': '日本筝',
            'Se': '瑟',
            'Kayagum': '伽倻琴',
            'Geomungo': '玄鹤琴',
            'Dan Tranh': '越南筝',
            'Đàn tranh': '越南筝',
            'Đàn bầu': '越南独弦琴',
            'Đàn nguyệt': '越南月琴',
            'Đàn tỳ bà': '越南琵琶',
            'Đàn nhị': '越南二胡',
            'Đàn tam': '越南三弦',
            'Đàn tứ': '越南四弦',
            'Đàn ngũ': '越南五弦',
            'Đàn lục': '越南六弦',
            'Đàn thập': '越南十弦',
            'Đàn đá': '越南石琴',
            'Đàn gáo': '越南葫芦琴',
            'Đàn năm': '越南五音琴',
            'Đàn sến': '越南竹琴',
            'Đàn tinh': '越南天琴',
            'Đàn độc huyền': '越南独弦琴',
            'Đàn tính': '越南天琴',
            'Đàn tam thập lục': '越南三十六弦琴',
            'Đàn bầu vọng cổ': '越南古乐独弦琴',
            'Đàn tranh cải tiến': '越南改良筝',
            'Đàn tranh 17 dây': '越南十七弦筝',
            'Đàn tranh 22 dây': '越南二十二弦筝',
            'Đàn tranh 25 dây': '越南二十五弦筝',
            'Đàn tranh 30 dây': '越南三十弦筝',
            'Đàn tranh 36 dây': '越南三十六弦筝',
            'Đàn tranh 44 dây': '越南四十四弦筝',
            'Đàn tranh 48 dây': '越南四十八弦筝',
            'Đàn tranh 52 dây': '越南五十二弦筝',
            'Đàn tranh 60 dây': '越南六十弦筝',
            'Đàn tranh 72 dây': '越南七十二弦筝',
            'Đàn tranh 88 dây': '越南八十八弦筝',
            'Đàn tranh 100 dây': '越南一百弦筝',
            'Đàn tranh 120 dây': '越南一百二十弦筝',
            'Đàn tranh 144 dây': '越南一百四十四弦筝',
            'Đàn tranh 160 dây': '越南一百六十弦筝',
            'Đàn tranh 200 dây': '越南二百弦筝',
            'Đàn tranh 240 dây': '越南二百四十弦筝',
            'Đàn tranh 300 dây': '越南三百弦筝',
            'Đàn tranh 400 dây': '越南四百弦筝',
            'Đàn tranh 500 dây': '越南五百弦筝',
            'Đàn tranh 600 dây': '越南六百弦筝',
            'Đàn tranh 700 dây': '越南七百弦筝',
            'Đàn tranh 800 dây': '越南八百弦筝',
            'Đàn tranh 900 dây': '越南九百弦筝',
            'Đàn tranh 1000 dây': '越南一千弦筝',
        }
        
        # 简单的翻译逻辑
        words = text.split()
        translated_words = []
        
        for word in words:
            # 检查是否在翻译映射表中
            if word in translation_map:
                translated_words.append(translation_map[word])
            else:
                # 如果没有找到翻译，保持原词
                translated_words.append(word)
        
        return ' '.join(translated_words)
    
    def stop(self):
        """停止翻译"""
        self.stop_flag = True